name: "Build and Deploy"

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

  # Permite rodar o workflow manualmente pela aba Actions
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas um deploy por vez, cancelando se houver um novo
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar GitHub Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Configurar Ruby e Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Instalar dependências
        run: bundle install

      - name: Construir o site Jekyll
        run: bundle exec jekyll build -d _site
        env:
          JEKYLL_ENV: "production"

      - name: Testar se o site foi gerado corretamente
        run: ls -l _site

      - name: Upload dos arquivos para o GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_site"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Fazer deploy para o GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
